// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWDl1gADxEplHbamtCawNT0NLkRwYR5P4',
    appId: '1:771550474384:web:f1f8f33fc340bdfa99a815',
    messagingSenderId: '771550474384',
    projectId: 'c-social-71e3a',
    authDomain: 'c-social-71e3a.firebaseapp.com',
    storageBucket: 'c-social-71e3a.appspot.com',
    measurementId: 'G-N2Z3476W1M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmJ2p-RtehhymPRgBq2_Vr76b7c_Dw6FA',
    appId: '1:771550474384:android:6fa091e305aae57099a815',
    messagingSenderId: '771550474384',
    projectId: 'c-social-71e3a',
    storageBucket: 'c-social-71e3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYFRE7K8PD8CRa8fKwemQwO4sZbzfc8Kc',
    appId: '1:771550474384:ios:9ec585d4cf37090d99a815',
    messagingSenderId: '771550474384',
    projectId: 'c-social-71e3a',
    storageBucket: 'c-social-71e3a.appspot.com',
    iosBundleId: 'com.ashmawi.social3c',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYFRE7K8PD8CRa8fKwemQwO4sZbzfc8Kc',
    appId: '1:771550474384:ios:9ec585d4cf37090d99a815',
    messagingSenderId: '771550474384',
    projectId: 'c-social-71e3a',
    storageBucket: 'c-social-71e3a.appspot.com',
    iosBundleId: 'com.ashmawi.social3c',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWDl1gADxEplHbamtCawNT0NLkRwYR5P4',
    appId: '1:771550474384:web:186a891c00c251e699a815',
    messagingSenderId: '771550474384',
    projectId: 'c-social-71e3a',
    authDomain: 'c-social-71e3a.firebaseapp.com',
    storageBucket: 'c-social-71e3a.appspot.com',
    measurementId: 'G-5HVDX1D4M7',
  );

}